[package]
name = "ioc"
version = "0.6.2"
authors = ["qrlpx <>"]

repository = "https://github.com/qrlpx/ioc"
description = "A simple IoC (Inversion of Control) container in Rust. "

license = "CC0-1.0"

[dependencies]
downcast = "^0.6"

